// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.




#include "BoxDragger.h"
#include "../RobotMap.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "../Commands/BoxDraggerDefaultCommand.h"

BoxDragger::BoxDragger() : Subsystem("BoxDragger") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	solenoidR = RobotMap::boxDraggersolenoidR;
	solenoidL = RobotMap::boxDraggersolenoidL;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
    
void BoxDragger::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	SetDefaultCommand(new BoxDraggerDefaultCommand());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}


// Put methods for controlling this subsystem
// here. Call these from Commands.
void BoxDragger::setState(Joystick *joy)
{
	if (joy->GetRawButton(6) && !(joy->GetRawButton(8)))
	{
		solenoidR->Set(true);
	}
	if (joy->GetRawButton(8) && !(joy->GetRawButton(6)))
	{
		solenoidR->Set(false);
	}
	if (joy->GetRawButton(5) && !(joy->GetRawButton(7)))
	{
		solenoidL->Set(true);
	}
	if (joy->GetRawButton(7) && !(joy->GetRawButton(5)))
	{
		solenoidL->Set(false);
	}
}
void BoxDragger::autoGrab()
{
	solenoidR->Set(true);
	solenoidL->Set(true);
}
