// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.




#include "Forklift.h"
#include "../RobotMap.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "../Commands/ForkliftDefaultComand.h"

Forklift::Forklift() : Subsystem("Forklift") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	speedControllerHorizontal = RobotMap::forkliftspeedControllerHorizontal;
	limitUp = RobotMap::forkliftlimitUp;
	limitDown = RobotMap::forkliftlimitDown;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	speedControllerVertical = RobotMap::forkliftspeedControllerVertical;
	PDP = RobotMap::forkliftPDP;
}
    
void Forklift::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	SetDefaultCommand(new ForkliftDefaultComand());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}


// Put methods for controlling this subsystem
// here. Call these from Commands.
void Forklift::forkliftLoop(Joystick *joy)
{
	float y;
	if ((joy->GetY() <= 0.2) && (joy->GetY() >= -0.2))
	{
		y = 0;
	}
	else
	{
		y = joy->GetY();
	}
	if (PDP->GetCurrent(5) <= 2)
	{
		speedControllerHorizontal->Set(joy->GetZ());
	}
	else
	{
		speedControllerHorizontal->Set(0);
		Wait(2);
	}
	speedControllerVertical->Set(y);
	SmartDashboard::PutNumber("forklift vertical", y);
	SmartDashboard::PutNumber("Grabber Amperage", PDP->GetCurrent(5));
}
