// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/BoxDraggerDefaultCommand.h"
#include "Commands/CompressorDefaultCommand.h"
#include "Commands/DriveTrainDefaultCommand.h"
#include "Commands/ForkliftDefaultComand.h"


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
	// Process operator interface input here.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

	joyAux = new Joystick(1);
	
	joyDriver = new Joystick(0);
	
     

        // SmartDashboard Buttons
	SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());

	SmartDashboard::PutData("DriveTrainDefaultCommand", new DriveTrainDefaultCommand());

	SmartDashboard::PutData("BoxDraggerDefaultCommand", new BoxDraggerDefaultCommand());

	SmartDashboard::PutData("CompressorDefaultCommand", new CompressorDefaultCommand());

	SmartDashboard::PutData("ForkliftDefaultComand", new ForkliftDefaultComand());


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

Joystick* OI::getjoyAux() {
	return joyAux;
}

Joystick* OI::getjoyDriver() {
	return joyDriver;
}


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
