// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/BoxDraggerDefaultCommand.h"
#include "Commands/CompressorDefaultCommand.h"
#include "Commands/DraggerLDCommand.h"
#include "Commands/DraggerLUCommand.h"
#include "Commands/DraggerRDCommand.h"
#include "Commands/DraggerRUCommand.h"
#include "Commands/DriveTrainDefaultCommand.h"
#include "Commands/ForkliftDefaultComand.h"
#include "Commands/ForkliftGrabCommand.h"
#include "Commands/ForkliftReleaseCommand.h"


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
	// Process operator interface input here.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

	joyAux = new Joystick(1);
	
	draggerLD = new JoystickButton(joyAux, 5);
	draggerLD->WhenPressed(new DraggerLDCommand());
	draggerLU = new JoystickButton(joyAux, 7);
	draggerLU->WhenPressed(new DraggerLUCommand());
	draggerRD = new JoystickButton(joyAux, 6);
	draggerRD->WhenPressed(new DraggerRDCommand());
	draggerRU = new JoystickButton(joyAux, 8);
	draggerRU->WhenPressed(new DraggerRUCommand());
	forkliftRelease = new JoystickButton(joyAux, 3);
	forkliftRelease->WhileHeld(new ForkliftReleaseCommand());
	forkliftGrab = new JoystickButton(joyAux, 1);
	forkliftGrab->WhileHeld(new ForkliftGrabCommand());
	joyDriver = new Joystick(0);
	
     

        // SmartDashboard Buttons
	SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());

	SmartDashboard::PutData("DriveTrainDefaultCommand", new DriveTrainDefaultCommand());

	SmartDashboard::PutData("BoxDraggerDefaultCommand", new BoxDraggerDefaultCommand());

	SmartDashboard::PutData("CompressorDefaultCommand", new CompressorDefaultCommand());

	SmartDashboard::PutData("ForkliftReleaseCommand", new ForkliftReleaseCommand());

	SmartDashboard::PutData("ForkliftGrabCommand", new ForkliftGrabCommand());

	SmartDashboard::PutData("ForkliftDefaultComand", new ForkliftDefaultComand());

	SmartDashboard::PutData("DraggerRUCommand", new DraggerRUCommand());

	SmartDashboard::PutData("DraggerRDCommand", new DraggerRDCommand());

	SmartDashboard::PutData("DraggerLUCommand", new DraggerLUCommand());

	SmartDashboard::PutData("DraggerLDCommand", new DraggerLDCommand());


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

Joystick* OI::getjoyAux() {
	return joyAux;
}

Joystick* OI::getjoyDriver() {
	return joyDriver;
}


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
